# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ../../obj/main.o $(RES)
LINKOBJ  = ../../obj/main.o $(RES)
LIBS =  -L"C:/MinGW/lib"  
INCS =  -I"C:/MinGW/include" 
CXXINCS =  -I"C:/MinGW/lib/gcc/mingw32/3.4.5/include"  -I"C:/MinGW/include/c++/3.4.5/backward"  -I"C:/MinGW/include/c++/3.4.5/mingw32"  -I"C:/MinGW/include/c++/3.4.5"  -I"C:/MinGW/include" 
BIN  = ../../bin/LSE_ShaderDump.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ../../bin/LSE_ShaderDump.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "..\..\bin\LSE_ShaderDump.exe" $(LIBS)

../../obj/main.o: ../../src/main.c
	$(CC) -c ../../src/main.c -o ../../obj/main.o $(CFLAGS)
